using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TajimiNow.Jma.Weather
{
    internal static class WeatherRegistry
    {
        private static readonly Dictionary<int, IWeather> weathers = new()
        {
            { 100, new SimpleWeather(100, "晴", "☀") },
            { 101, new OccasionalWeather(101, "晴時々曇", "☀", "☁") },
            { 102, new OccasionalWeather(102, "晴一時雨", "☀", "☂") },
            { 103, new OccasionalWeather(103, "晴時々雨", "☀", "☂") },
            { 104, new OccasionalWeather(104, "晴一時雪", "☀", "❄") },
            { 105, new OccasionalWeather(105, "晴時々雪", "☀", "❄") },
            { 106, new OccasionalWeather(106, "晴一時雨か雪", "☀", "☂❄") },
            { 107, new OccasionalWeather(107, "晴時々雨か雪", "☀", "☂❄") },
            { 108, new OccasionalWeather(108, "晴一時雨か雷雨", "☀", "☂⚡") },
            { 110, new LaterWeather(110, "晴後時々曇", "☀", "☁") },
            { 111, new LaterWeather(111, "晴後曇", "☀", "☁") },
            { 112, new LaterWeather(112, "晴後一時雨", "☀", "☂") },
            { 113, new LaterWeather(113, "晴後時々雨", "☀", "☂") },
            { 114, new LaterWeather(114, "晴後雨", "☀", "☂") },
            { 115, new LaterWeather(115, "晴後一時雪", "☀", "❄") },
            { 116, new LaterWeather(116, "晴後時々雪", "☀", "❄") },
            { 117, new LaterWeather(117, "晴後雪", "☀", "❄") },
            { 118, new LaterWeather(118, "晴後雨か雪", "☀", "☂❄") },
            { 119, new LaterWeather(119, "晴後雨か雷雨", "☀", "☂⚡") },
            { 120, new OccasionalWeather(120, "晴朝夕一時雨", "☀", "☂") },
            { 121, new OccasionalWeather(121, "晴朝の内一時雨", "☀", "☂") },
            { 122, new LaterWeather(122, "晴夕方一時雨", "☀", "☂") },
            { 123, new OccasionalWeather(123, "晴山沿い雷雨", "☀", "☂⚡") },
            { 124, new OccasionalWeather(124, "晴山沿い雪", "☀", "❄") },
            { 125, new LaterWeather(125, "晴午後は雷雨", "☀", "☂⚡") },
            { 126, new LaterWeather(126, "晴昼頃から雨", "☀", "☂") },
            { 127, new LaterWeather(127, "晴夕方から雨", "☀", "☂") },
            { 128, new LaterWeather(128, "晴夜は雨", "☀", "☂") },
            { 130, new SimpleWeather(130, "朝の内霧後晴", "☀") },
            { 131, new SimpleWeather(131, "晴明け方霧", "☀") },
            { 132, new OccasionalWeather(132, "晴朝夕曇", "☀", "☁") },
            { 140, new OccasionalWeather(140, "晴時々雨で雷を伴う", "☀", "☂⚡") },
            { 160, new OccasionalWeather(160, "晴一時雪か雨", "☀", "❄☂") },
            { 170, new OccasionalWeather(170, "晴時々雪か雨", "☀", "❄☂") },
            { 181, new LaterWeather(181, "晴後雪か雨", "☀", "❄☂") },
            { 200, new SimpleWeather(200, "曇", "☁") },
            { 201, new OccasionalWeather(201, "曇時々晴", "☁", "☀") },
            { 202, new OccasionalWeather(202, "曇一時雨", "☁", "☂") },
            { 203, new OccasionalWeather(203, "曇時々雨", "☁", "☂") },
            { 204, new OccasionalWeather(204, "曇一時雪", "☁", "❄") },
            { 205, new OccasionalWeather(205, "曇時々雪", "☁", "❄") },
            { 206, new OccasionalWeather(206, "曇一時雨か雪", "☁", "☂❄") },
            { 207, new OccasionalWeather(207, "曇時々雨か雪", "☁", "☂❄") },
            { 208, new OccasionalWeather(208, "曇一時雨か雷雨", "☁", "☂⚡") },
            { 209, new SimpleWeather(209, "霧", "☁") },
            { 210, new LaterWeather(210, "曇後時々晴", "☁", "☀") },
            { 211, new LaterWeather(211, "曇後晴", "☁", "☀") },
            { 212, new LaterWeather(212, "曇後一時雨", "☁", "☂") },
            { 213, new LaterWeather(213, "曇後時々雨", "☁", "☂") },
            { 214, new LaterWeather(214, "曇後雨", "☁", "☂") },
            { 215, new LaterWeather(215, "曇後一時雪", "☁", "❄") },
            { 216, new LaterWeather(216, "曇後時々雪", "☁", "❄") },
            { 217, new LaterWeather(217, "曇後雪", "☁", "❄") },
            { 218, new LaterWeather(218, "曇後雨か雪", "☁", "☂❄") },
            { 219, new LaterWeather(219, "曇後雨か雷雨", "☁", "☂⚡") },
            { 220, new OccasionalWeather(220, "曇朝夕一時雨", "☁", "☂") },
            { 221, new OccasionalWeather(221, "曇朝の内一時雨", "☁", "☂") },
            { 222, new LaterWeather(222, "曇夕方一時雨", "☁", "☂") },
            { 223, new OccasionalWeather(223, "曇日中時々晴", "☁", "☀") },
            { 224, new LaterWeather(224, "曇昼頃から雨", "☁", "☂") },
            { 225, new LaterWeather(225, "曇夕方から雨", "☁", "☂") },
            { 226, new LaterWeather(226, "曇夜は雨", "☁", "☂") },
            { 228, new LaterWeather(228, "曇昼頃から雪", "☁", "❄") },
            { 229, new LaterWeather(229, "曇夕方から雪", "☁", "❄") },
            { 230, new LaterWeather(230, "曇夜は雪", "☁", "❄") },
            { 231, new OccasionalWeather(231, "曇海上海岸は霧か霧雨", "☁", "☂") },
            { 240, new OccasionalWeather(240, "曇時々雨で雷を伴う", "☁", "☂⚡") },
            { 250, new OccasionalWeather(250, "曇時々雪で雷を伴う", "☁", "❄⚡") },
            { 260, new OccasionalWeather(260, "曇一時雪か雨", "☁", "❄☂") },
            { 270, new OccasionalWeather(270, "曇時々雪か雨", "☁", "❄☂") },
            { 281, new LaterWeather(281, "曇後雪か雨", "☁", "❄☂") },
            { 300, new SimpleWeather(300, "雨", "☂") },
            { 301, new OccasionalWeather(301, "雨時々晴", "☂", "☀") },
            { 302, new OccasionalWeather(302, "雨時々止む", "☂", "☁") },
            { 303, new OccasionalWeather(303, "雨時々雪", "☂", "❄") },
            { 304, new SimpleWeather(304, "雨か雪", "☂❄") },
            { 306, new SimpleWeather(306, "大雨", "☂") },
            { 308, new SimpleWeather(308, "雨で暴風を伴う", "☂💨") },
            { 309, new OccasionalWeather(309, "雨一時雪", "☂", "❄") },
            { 311, new LaterWeather(311, "雨後晴", "☂", "☀") },
            { 313, new LaterWeather(313, "雨後曇", "☂", "☁") },
            { 314, new LaterWeather(314, "雨後時々雪", "☂", "❄") },
            { 315, new LaterWeather(315, "雨後雪", "☂", "❄") },
            { 316, new LaterWeather(316, "雨か雪後晴", "☂❄", "☀") },
            { 317, new LaterWeather(317, "雨か雪後曇", "☂❄", "☁") },
            { 320, new LaterWeather(320, "朝の内雨後晴", "☂", "☀") },
            { 321, new LaterWeather(321, "朝の内雨後曇", "☂", "☁") },
            { 322, new OccasionalWeather(322, "雨朝晩一時雪", "☂", "❄") },
            { 323, new LaterWeather(323, "雨昼頃から晴", "☂", "☀") },
            { 324, new LaterWeather(324, "雨夕方から晴", "☂", "☀") },
            { 325, new LaterWeather(325, "雨夜は晴", "☂", "☀") },
            { 326, new LaterWeather(326, "雨夕方から雪", "☂", "❄") },
            { 327, new LaterWeather(327, "雨夜は雪", "☂", "❄") },
            { 328, new SimpleWeather(328, "雨一時強く降る", "☂") },
            { 329, new SimpleWeather(329, "雨一時みぞれ", "☂") },
            { 340, new SimpleWeather(340, "雪か雨", "❄☂") },
            { 350, new SimpleWeather(350, "雨で雷を伴う", "☂⚡") },
            { 361, new LaterWeather(361, "雪か雨後晴", "❄☂", "☀") },
            { 371, new LaterWeather(371, "雪か雨後曇", "❄☂", "☁") },
            { 400, new SimpleWeather(400, "雪", "❄") },
            { 401, new OccasionalWeather(401, "雪時々晴", "❄", "☀") },
            { 402, new OccasionalWeather(402, "雪時々止む", "❄", "☁") },
            { 403, new OccasionalWeather(403, "雪時々雨", "❄", "☂") },
            { 405, new SimpleWeather(405, "大雪", "❄") },
            { 406, new SimpleWeather(406, "風雪強い", "❄💨") },
            { 407, new SimpleWeather(407, "暴風雪", "❄💨") },
            { 409, new OccasionalWeather(409, "雪一時雨", "❄", "☂") },
            { 411, new LaterWeather(411, "雪後晴", "❄", "☀") },
            { 413, new LaterWeather(413, "雪後曇", "❄", "☁") },
            { 414, new LaterWeather(414, "雪後雨", "❄", "☂") },
            { 420, new LaterWeather(420, "朝の内雪後晴", "❄", "☀") },
            { 421, new LaterWeather(421, "朝の内雪後曇", "❄", "☁") },
            { 422, new LaterWeather(422, "雪昼頃から雨", "❄", "☂") },
            { 423, new LaterWeather(423, "雪夕方から雨", "❄", "☂") },
            { 425, new SimpleWeather(425, "雪一時強く降る", "❄") },
            { 426, new SimpleWeather(426, "雪後みぞれ", "❄") },
            { 427, new SimpleWeather(427, "雪一時みぞれ", "❄") },
            { 450, new SimpleWeather(450, "雪で雷を伴う", "❄⚡") }
        };

        public static IWeather GetFromCode(int code) => weathers[code];
    }
}
